# GENERATED. Do not edit this file in the tap.
#
# The source is desktop/homebrew/ltb.rb.tmpl in gpulogyai/letthemchat, and
# scripts/publish-cask.sh renders it during a Mac release — the version and both
# checksums come from the artifacts that were actually uploaded, so an edit made
# here is overwritten by the next release.
#
# It is generated rather than hand-maintained for the reason this tap sat at
# 1.1.43 while the app shipped 1.1.46: a file kept in a second repository is a
# file somebody has to remember, and nobody did.
#
# The rule it encodes: the cask carries no copy of anything. It links to the
# script inside the app bundle, and bin/letthembuild in that repository is the
# only copy of that script anywhere.
#
# THE TOKEN IS `ltb`, NOT `letthembuild`, AND THAT IS DELIBERATE.
# A cask's token is its install name, and Homebrew has no alias mechanism for
# casks — Aliases/ in a tap maps to formula names only. So `brew install ltb`
# is possible only by naming the cask that. The old token still works: the
# tap's cask_renames.json maps letthembuild -> ltb, which Homebrew resolves as
# a rename and tells the user about.
cask "ltb" do
  version "1.1.68"

  on_arm do
    sha256 "d3ebbeaab4241b1a5e2572fee3a2d9e1269c5d4ad12e0ab884375dcacb0ae723"

    url "https://letthembuild.com/updates/LetThemBuild-#{version}-arm64-mac.zip"
  end
  on_intel do
    sha256 "ec8fe7d0389ffa09358954a2bf89adf6abe6d6985c01bb748bd2e0a162a6feba"

    url "https://letthembuild.com/updates/LetThemBuild-#{version}-x64-mac.zip"
  end

  name "LetThemBuild"
  desc "AI group that builds and reviews in your checkout, with hands"
  homepage "https://letthembuild.com/"

  # The zips out of /updates, not the .dmg off the download page.
  #
  # A cask needs a URL whose contents never change, because it pins a checksum
  # to it. The download page's names are deliberately the opposite — stable
  # names, replaced in place every release, so a link in an email keeps
  # working — and pointing a cask at one means every `brew install` between a
  # release and a tap bump fails on a checksum mismatch, with a cached copy
  # making it worse. The updater's artifacts are already versioned, immutable
  # and served with a year of cache; they are notarized and stapled from the
  # same build as the .dmg, so this costs nothing and uploads nothing extra.
  livecheck do
    url "https://letthembuild.com/updates/latest-mac.yml"
    strategy :electron_builder
  end

  # The app updates itself through electron-updater. Without this, brew reports
  # a self-updated install as outdated forever and `brew upgrade` reinstalls an
  # older build over a newer one.
  auto_updates true
  # A bare symbol here means "or newer", not "exactly" — Homebrew parses this
  # stanza with a >= comparator, and `brew style` rewrites the explicit form to
  # this one. The version is Electron 43's own LSMinimumSystemVersion, read out
  # of the framework rather than guessed: macOS 12. The cask said Ventura,
  # which turned away Monterey users whose machines run the app perfectly well.
  depends_on macos: :monterey

  app "LetThemBuild.app"
  # `ltb` and `letthembuild`, both pointing INTO the installed app.
  #
  # Up to 1.1.43 the script existed only inside app.asar, where nothing outside
  # the app can reach it, so the cask wrote its own copy at install time — a
  # second, hand-pasted copy of a script whose whole design is that there is
  # exactly one. The build now places it unpacked at Contents/Resources/bin,
  # before signing, so the link goes straight to it: the command a user runs is
  # always the one that shipped with the app they have installed, and there is
  # nothing here to drift out of date.
  binary "#{appdir}/LetThemBuild.app/Contents/Resources/bin/letthembuild"
  binary "#{appdir}/LetThemBuild.app/Contents/Resources/bin/letthembuild", target: "ltb"

  # Stand aside the app's own CLI installer — but only where it is ours.
  #
  # Settings -> Install CLI writes `letthembuild` (a real file) and `ltb` (a
  # symlink to it) into the first writable directory on the PATH, and
  # cliTargets in main.js offers /opt/homebrew/bin — which is exactly where a
  # binary stanza lands. Homebrew RAISES rather than overwrites when a Binary
  # target already exists, and --force does not help: its overwrite path
  # requires the existing target to be a symlink into this cask, and the in-app
  # installer writes a real file. So `brew install --cask ltb` failed outright
  # for anyone who had used the in-app installer first — the advertised command,
  # broken for exactly the people most likely to have tried the other way.
  #
  # Removed only when demonstrably ours: a regular file carrying the
  # LETTHEMBUILD_APP marker, or a symlink named for our own script. That is the
  # test uninstallCli already applies, and for the same reason — there is
  # another tool called ltb in the world, and it is not ours to delete.
  # Anything under Cellar or Caskroom belongs to Homebrew; those are left alone
  # so it can report the conflict itself.
  #
  # Placed after the artifacts and run before them: `preflight` executes ahead
  # of the install, but the cask stanza order puts it here.
  preflight do
    ["ltb", "letthembuild"].each do |name|
      target = Pathname.new("#{HOMEBREW_PREFIX}/bin/#{name}")
      # symlink? as well as exist?, because exist? follows a link and a dangling
      # one still occupies the name Homebrew is about to want.
      next if !target.symlink? && !target.exist?

      link = target.symlink? ? target.readlink.to_s : nil
      next if link&.include?("/Cellar/") || link&.include?("/Caskroom/")

      ours = if link
        File.basename(link) == "letthembuild"
      else
        target.file? && target.size < 65_536 && target.read.include?("LETTHEMBUILD_APP")
      end
      next unless ours

      opoo "Replacing #{target}, which LetThemBuild's own Settings pane installed."
      FileUtils.rm target
    end
  end

  # An upgrade that replaces a running .app leaves the old one running against
  # new resources; quitting first is what makes `brew upgrade` safe to run
  # while the app is open.
  uninstall quit: "com.letthemchat.desktop"

  # `brew uninstall --zap`. Application Support is "LetThemChat" — NOT the
  # product name. main.js line 12 calls app.setName("LetThemChat"), and
  # Electron keys userData on the app name, so that is where every setting,
  # session and stored key actually lives. This was "corrected" to
  # LetThemBuild once, on the productName theory, without checking the disk;
  # the original value had been right all along. The test now derives the
  # path from app.setName itself so the two cannot drift apart again.
  #
  # ~/Documents/LetThemBuild is deliberately absent: those are the user's own
  # checkouts and worktrees, which is their work, not this app's state.
  zap trash: [
    "~/Library/Application Support/LetThemChat",
    "~/Library/Caches/com.letthemchat.desktop",
    "~/Library/HTTPStorages/com.letthemchat.desktop",
    "~/Library/Logs/letthembuild-cursor.log",
    "~/Library/Logs/letthembuild-vscode.log",
    "~/Library/Preferences/com.letthemchat.desktop.plist",
    "~/Library/Saved Application State/com.letthemchat.desktop.savedState",
  ]

  caveats <<~EOS
    The room's seats, keys and settings are configured in the app itself —
    open LetThemBuild once before using `ltb` from a terminal.
  EOS
end
